---
- name: "Install k8s worker node"
  hosts: all
  vars_files: 
    - vars/slave-variables
    - vars/host_values
  tasks:
#Update packages and install needed
    - name: "k8s worker node ready with kubernetes repo"
      copy:
        src: templates/kubernetes.repo
        dest: /etc/yum.repos.d/kubernetes.repo

    - name: "k8s worker node install yum-utils"
      yum:
        name: yum-utils
        state: latest
        update_cache: True

    - name: "k8s worker node add repos to docker"
      shell:
        cmd: 'yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo'

    - name: rp_filter
      shell:
        cmd: 'echo 1 > /proc/sys/net/ipv4/conf/all/rp_filter'


    - name: "k8s worker node update all packages"
      yum:
        name: "*"
        state: present
        update_cache: true
        
    - name: " {{ item.name }} install packages"
      yum:
        name: "{{ item.name }}"
        state: latest
        update_cache: True

      when: item.required == True
      loop: "{{ packages }}"

#Start and enable docker and kubelet
    - name: "k8s worker node start and enable keep alive and ha proxy"
      systemd:
        name: docker
        state: restarted
        enabled: yes

    - systemd:
        name: kubelet
        state: restarted
        enabled: yes

    - name: "k8s worker node replace line"
      lineinfile:
        path: /usr/lib/systemd/system/docker.service
        regexp: '^(.*)ExecStart=(.*)$'
        line: 'ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --exec-opt native.cgroupdriver=systemd'
        backrefs: yes

    - name: "k8s worker node create environment"
      file:
        path: /etc/systemd/system/kubelet.service.d/
        owner: root
        group: root
        state: directory
        mode: '0755'

    - name: " k8s worker node memory and accounting"
      shell:
        cmd: 'echo -e "[Service]\nCPUAccounting=true\nMemoryAccounting=true" > /etc/systemd/system/kubelet.service.d/11-cgroups.conf'



#NTP update
    - name: "k8s worker node NTP Date to crone"
      cron:
        name: "Time Update"
        minute: "*"
        job: "ntpdate time.apple.com"

#Disable SE Linux
    - name: "k8s worker node disable SELinux"
      selinux:
        state: disabled
      register: sestatus


#Add hosts file contents
    - name: "k8s worker node create copy the content"
      template: 
        src: templates/remote_hosts.tmpl 
        dest: /etc/hosts
        mode: 644
        owner: root
        group: root
        backup: yes

# Add firewall rules
    - name: "k8s worker node implement rules"
      firewalld:
        port: "{{item.port}}/{{item.proto}}"
        permanent: yes
        state: enabled
      loop: "{{ m_ports }}"

#Do a reboot
    - name: "k8s worker node reboot"
      reboot:
      when: sestatus.changed == true

#Wait for the server to boot back
    - name: "k8s worker node Wait for server to restart"
      local_action:
        module: wait_for
          host={{ inventory_hostname }}
          port=22
          delay=10
          timeout=60
      when: sestatus.changed == true

#Clean old kernels
    - name: "k8s worker node cleanup old kernels"
      command: 'package-cleanup --oldkernels --count=1'

# Enable modprob br_netfilter and forward rules
    - name: "k8s worker node modprob br_netfilter and forward rules"
      shell:
        cmd: 'modprobe br_netfilter'
    - shell:
        cmd: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"
    - shell:
        cmd: "echo '1' > /proc/sys/net/ipv4/ip_forward"

#Start and enable docker and kubelet
    - name: "k8s worker node Start and enable keep alive and ha proxy"
      systemd:
        name: docker
        state: restarted
        enabled: yes

    - systemd:
        name: kubelet
        state: restarted
        enabled: yes

    - name: "k8s worker node delete Containerd toml"
      file:
        path: /etc/containerd/config.toml
        state: absent

    - name: "k8s worker node restart the containerd"
      systemd:
        name: containerd
        state: restarted
        enabled: yes

    - name: "k8s worker node deploy the slave connection stringy"
      command: 'sh slave_string.sh'

    - name: "k8s worker node ip table rule1"
      shell:
        cmd: 'iptables -D  INPUT -j REJECT --reject-with icmp-host-prohibited'

    - name: "k8s worker node ip table rule2"
      shell:
        cmd: 'iptables -D  FORWARD -j REJECT --reject-with icmp-host-prohibited'
